### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by amanuel1995** [amanuel1995/MI-449-SS17-741-html-more-kinds-of-content-OSB7Pe#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://amanuel1995.github.io/MI-449-SS17-741-html-more-kinds-of-content-OSB7Pe/) and meets the following criteria:

- [x] Include [a haiku](http://www.kidzone.ws/poetry/haiku.htm), describing the feelings this product will evoke (with `br` elements to add new lines where appropriate)
- [x] [Create and download a sound effect file](http://sfbgames.com/chiptone/) for what the game will sound like when you win, then include an audio player in the page so users can hear the sample
- [x] Include a table comparing which features your game has in comparison to competitors (these competitors may be real or made up)
- [x] Include a demo video from YouTube, but featuring a completely unrelated animal being cute (not getting hurt!)

**Comment by KatieMFritz** [comment]
Fancy Bootstrap work! 😮 

Unfortunately, there are a couple of errors when I run the site through the [W3 Validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Famanuel1995.github.io%2FMI-449-SS17-741-html-more-kinds-of-content-OSB7Pe%2F). Could you please fix those, than resubmit?

**Comment by amanuel1995** [comment]
Thank you!! I have noticed the frameborder thingy being obsolete before and I just removed the CDNs that I did not use for the page. No errors now.

**Comment by stuartpearman** [comment]
Hey Amanuel, I'm helping Katie out with code reviews today. Looks like you fixed any errors! :shipit:

**Comment by amanuel1995** [comment]
Thank you!
